In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('../data/raw/products.csv')
df.head()

   id language                                           product category
0   1       id           laptop Lenovo ThinkPad X1 Carbon Gen 11       IT
1   2       id               PC desktop Dell OptiPlex 7010 Tower       IT
2   3       id             monitor eksternal ASUS ProArt PA278CV       IT
3   4       id                    mini PC ASUS ExpertCenter PN64       IT
4   5       id  router Wi-Fi kantor TP-Link Archer AX90 (AX6600)       IT

In [3]:
df.shape

(200, 4)

In [4]:
df.head(10)

   id language                                            product category
0   1       id            laptop Lenovo ThinkPad X1 Carbon Gen 11       IT
1   2       id                PC desktop Dell OptiPlex 7010 Tower       IT
2   3       id              monitor eksternal ASUS ProArt PA278CV       IT
3   4       id                     mini PC ASUS ExpertCenter PN64       IT
4   5       id   router Wi-Fi kantor TP-Link Archer AX90 (AX6600)       IT
5   6       id                 network switch Cisco CBS250-24T-4G       IT
6   7       id  network attached storage (NAS) Synology DiskSt...       IT
7   8       id   printer multi-fungsi HP LaserJet Pro MFP M428fdn       IT
8   9       id          scanner dokumen Epson WorkForce DS-530 II       IT
9  10       id               keyboard wireless Logitech MX Keys S       IT

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        200 non-null    int64
 1   language  200 non-null    str
 2   product   200 non-null    str
 3   category  200 non-null    str
dtypes: int64(1), str(3)
memory usage: 6.4 KB

In [6]:
df['language'].value_counts()

language
id    100
zh    100
Name: count, dtype: int64

In [7]:
df['category'].value_counts()

category
IT                  40
Office Supplies     40
Electrical          40
Tools & Hardware    40
Safety Equipment    40
Name: count, dtype: int64

In [8]:
pd.crosstab(df['language'], df['category'])

category  Electrical  IT  Office Supplies  Safety Equipment  Tools & Hardware
language
id                20  20               20                20                20
zh                20  20               20                20                20